version: "3.7"


services:
  postgres:
    restart: always
    container_name: postgres_geneesplaats_nl_${ENVIRONMENT}
    image: postgres:${POSTGRES_GENEESPLAATS_NL_VERSION}
    env_file: ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    networks:
      - postgres-network


  django:
    container_name: django_geneesplaats_nl_${ENVIRONMENT}
    image: spikkie/django_geneesplaats_nl:${DJANGO_GENEESPLAATS_NL_VERSION}
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    depends_on:
      - postgres
    env_file: ./.env
    ports:
      - "8001:8001"
    volumes:
   
      - static_volume:/app/static_cdn/static_root/
      - media_volume:/app/static_cdn/media_root/
 
    networks:
      - postgres-network


      
  react:
    container_name: react_geneesplaats_nl_${ENVIRONMENT}
    image: spikkie/react_geneesplaats_nl:${DJANGO_GENEESPLAATS_NL_VERSION}
    restart: always
    build:
      context: ./frontend
      dockerfile: ../docker/react/Dockerfile
    depends_on:
      - django 
    env_file: ./.env
    expose:
      - 3000    

    networks:
      - postgres-network
      
  nginx:
    restart: always
    image: spikkie/nginx_geneesplaats_nl:${NGINX_GENEESPLAATS_NL_VERSION}
    container_name: nginx_geneesplaats_nl
    build: ./docker/nginx/

    #todo
    #volumes:
    #  - ./nginx/:/etc/nginx/conf.d
    #  - ./logs/:/code/logs

    volumes:
      - static_volume:/app/static_cdn/static_root/
      - media_volume:/app/static_cdn/media_root/
    
    ports:
      - 80:80
    depends_on:
      - react
    env_file: ./.env
    networks:
      - postgres-network

volumes:
  postgres_data: {}
  postgres_backup: {}
  static_volume: {}
  media_volume: {}


networks:
  postgres-network:
    driver: bridge

