version: "3.8"

services:
  postgres:
    restart: always
    container_name: ${POSTGRES_REPOSITORY}_test
    image: ${POSTGRES_GENEESPLAATS_NL_IMAGE}
    volumes:
      - postgres_data_dev_test:/var/lib/postgresql/data
      - postgres_backup_dev_test:/backups
    # networks:
      # - postgres-network
    ports:
      - "5432:5432"
    env_file:
      - ./.env

volumes:
  postgres_data_dev_test: {}
  postgres_backup_dev_test: {}
  
# networks:
#   postgres-network:
#     driver: bridge
