services:
  postgres:
    container_name: postgres_geneesplaats_nl_production_prod
    environment:
      DATABASE_URL: postgres://production_geneesplaats_nl_user:1qiovWPEcmbJ@postgres:5432/production_geneesplaats_nl
      DEBUG: '1'
      DOCKERID: spikkie
      ENVIRONMENT: production
      NODE_ENV: production
      POSTGRES_DB: production_geneesplaats_nl
      POSTGRES_GENEESPLAATS_NL_IMAGE: postgres:12.1-alpine
      POSTGRES_GENEESPLAATS_NL_VERSION: latest
      POSTGRES_PASSWORD: 1qiovWPEcmbJ
      POSTGRES_REPOSITORY: postgres_geneesplaats_nl_production
      POSTGRES_USER: production_geneesplaats_nl_user
      REACT_APP_BASE_URL: ''
      REACT_APP_EXPOSE_PORT: '8000'
      REACT_APP_TEST: TEST
      REACT_GENEESPLAATS_NL_IMAGE: spikkie/react_geneesplaats_nl_production
      REACT_GENEESPLAATS_NL_VERSION: latest
      REACT_REPOSITORY: react_geneesplaats_nl_production
      SECRET_KEY: dsFxxMjPZJBEJRiWdTCG8FgT2JVTaA2ww4Oj2D3uWo7V29BDND
    image: postgres:12.1-alpine
    ports:
    - published: 5432
      target: 5432
    restart: always
    volumes:
    - postgres_data_prod:/var/lib/postgresql/data:rw
    - postgres_backup_prod:/backups:rw
  react:
    build:
      context: /home/spikkieroot/projects/graphql/graphbook
      dockerfile: ./docker/prod/Dockerfile
    container_name: react_geneesplaats_nl_production
    depends_on:
    - postgres
    environment:
      AWS_ACCESS_KEY_ID: AKIAXV2OR6BHPKAHQK3D
      AWS_SECRET_ACCESS_KEY: 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
      DATABASE_URL: postgres://production_geneesplaats_nl_user:1qiovWPEcmbJ@postgres:5432/production_geneesplaats_nl
      DEBUG: '1'
      DOCKERID: spikkie
      ENVIRONMENT: production
      JWT_SECRET: awv4BcIzsRysXkhoSAb8t8lNENgXSqBruVlLwd45kGdYjeJHLap9LUJ1t9DTdw36DvLcWs3qEkPyCY6vOyNljlh2Er952h2gDzYwG82rs1qfTzdVIg89KTaQ4SWI1YGY
      NODE_ENV: development
      PORT: '8000'
      POSTGRES_DB: production_geneesplaats_nl
      POSTGRES_GENEESPLAATS_NL_IMAGE: postgres:12.1-alpine
      POSTGRES_GENEESPLAATS_NL_VERSION: latest
      POSTGRES_PASSWORD: 1qiovWPEcmbJ
      POSTGRES_REPOSITORY: postgres_geneesplaats_nl_production
      POSTGRES_USER: production_geneesplaats_nl_user
      REACT_APP_BASE_URL: ''
      REACT_APP_EXPOSE_PORT: '8000'
      REACT_APP_TEST: TEST
      REACT_GENEESPLAATS_NL_IMAGE: spikkie/react_geneesplaats_nl_production
      REACT_GENEESPLAATS_NL_VERSION: latest
      REACT_REPOSITORY: react_geneesplaats_nl_production
      SECRET_KEY: nngC9ZO6LCOHqjXo3sqhP4gWHiTLHyCZXaK3iwRq2U7s7gq9pV
    expose:
    - '8000'
    image: spikkie/react_geneesplaats_nl_production:latest
    ports:
    - published: 8000
      target: 8000
    restart: always
version: '3.7'
volumes:
  postgres_backup_prod: {}
  postgres_data_prod: {}

