apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-volume-pv
  labels:
    type: local
    mnt: media-volume-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/mnt/media-volume-pv"
