apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-development.yml --controller deployment -o kompose_production_2
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: react
  name: react
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-development.yml --controller deployment -o kompose_production_2
        kompose.version: 1.20.0 (f3d54d784)
      creationTimestamp: null
      labels:
        io.kompose.network/postgres-network: "true"
        io.kompose.service: react
    spec:
      containers:
      - image: 'spikkie/react_geneesplaats_nl:'
        name: react-geneesplaats-nl-
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}
