apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: static-my-proj-volume
  name: static-my-proj-volume
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  selector: 
    matchLabels:
      mnt: static-my-proj-volume-pv
status: {}