apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 
  name: media-volume-emptydir
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi


