apiVersion: v1
kind: PersistentVolumeClaim
metadata:

  name: postgres-backup-emptydir
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi


