apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-emptydir
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi


