apiVersion: v1
kind: PersistentVolumeClaim
metadata:


  name: static-my-proj-volume
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi


